# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: slice_ui
version: '2.0'
author: Sascha Weidner
supportpage: http://www.factorylabs.ch

requires:
  packages:
    structure: '>=5.0 alpha'

page:
    title: 'translate:title'
    pjax: true
    icon: rex-icon rex-icon-copy
    subpages:
        settings: { title: 'translate:settings', perm: slice_ui[settings]}
        help: { title: 'translate:help' }
