package: slice_ui
version: '2.1.2'
author: Sascha Weidner
supportpage: http://www.factorylabs.ch

requires:
  packages:
    structure: '>=2.0.0-beta1'

page:
    title: 'translate:title'
    pjax: true
    perm: slice_ui[]
    icon: rex-icon rex-icon-copy
    subpages:
        settings: { title: 'translate:settings', perm: slice_ui[settings]}
        help: { title: 'translate:help'}
